extends: google
parserOptions:
    ecmaVersion: 7
rules:
    camelcase: off
    comma-dangle: off
    indent: off
    no-var: off
    no-unused-vars: off
    no-throw-literal: off
    new-cap: off
    max-len: off
    one-var: off
    quotes: off
    require-jsdoc: off
