dist: xenial
install:
    - sudo cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - cpanm Path::Tiny
    - gem install rake
    - gem install rubocop
    - bash -x bin/install-npm-deps.sh
script:
    - PATH="$PATH:$PWD/node_modules/.bin"
    - rake
    - rake test
